# Generated by Django 3.2.3 on 2022-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_auto_20221016_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
