# Generated by Django 3.2.3 on 2022-05-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_persona_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=150, null=True)),
                ('auth_date', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona')),
            ],
        ),
    ]
