# Generated by Django 3.2.3 on 2021-05-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(blank=True, null=True)),
                ('cantidad_corderos', models.IntegerField(blank=True, null=True)),
                ('cantidad_ovejas', models.IntegerField(blank=True, null=True)),
                ('cantidad_carneros', models.IntegerField(blank=True, null=True)),
                ('cantidad_pariciones', models.IntegerField(blank=True, null=True)),
                ('cantidad_muertes_corderos', models.IntegerField(blank=True, null=True)),
                ('cantidad_lana_producida', models.IntegerField(blank=True, null=True)),
                ('cantidad_carne_producida', models.IntegerField(blank=True, null=True)),
                ('rinde_lana', models.IntegerField(blank=True, null=True)),
                ('finura_lana', models.IntegerField(blank=True, null=True)),
                ('campo', models.ForeignKey(db_column='campo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campo.campo')),
            ],
        ),
    ]
