# Generated by Django 3.2.3 on 2021-07-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproduccion',
            name='campo',
            field=models.ForeignKey(db_column='campo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_produccion_set', to='campo.campo'),
        ),
    ]
