{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
},
{
'periodo': 0,
'temperatura_minima': 0,
'temperatura_maxima': 0,
'temperatura': 0,
'humedad': 0,
'velocidad_viento': 0,
'direccion_viento': 0,
'mm_lluvia': 0,
'localidad': 0,
'corderos': 0,
'ovejas': 0,
'carneros': 0,
'pariciones': 0,
'muertes_corderos': 0,
'lana_producida': 0,
'carne_producida': 0,
'rinde_lana': 0,
'finura_lana': 0,
}