# Generated by Django 3.2.3 on 2022-10-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(blank=True, null=True)),
                ('temperatura_minima', models.FloatField(blank=True, null=True)),
                ('temperatura_media', models.FloatField(blank=True, null=True)),
                ('temperatura_maxima', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('velocidad_viento', models.FloatField(blank=True, null=True)),
                ('direccion_viento', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidad_max_viento', models.FloatField(blank=True, null=True)),
                ('barometro', models.FloatField(blank=True, null=True)),
                ('mm_lluvia', models.FloatField(blank=True, null=True)),
                ('radiacion_solar', models.FloatField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_climaticos', to='campo.campo')),
            ],
        ),
    ]
