# Generated by Django 3.2.3 on 2021-05-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sonda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('ubicacion_exacta', models.CharField(blank=True, max_length=30, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('pertenencia', models.CharField(choices=[('INTA', 'INTA'), ('PARTICULAR', 'PARTICULAR')], default='1', max_length=15)),
                ('inicio_actividad', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=30, null=True)),
                ('id_inta', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(blank=True, null=True)),
                ('temperatura_minima', models.FloatField(blank=True, null=True)),
                ('temperatura_media', models.FloatField(blank=True, null=True)),
                ('temperatura_maxima', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('velocidad_viento', models.FloatField(blank=True, null=True)),
                ('direccion_viento', models.FloatField(blank=True, null=True)),
                ('velocidad_max_viento', models.FloatField(blank=True, null=True)),
                ('barometro', models.FloatField(blank=True, null=True)),
                ('mm_lluvia', models.FloatField(blank=True, null=True)),
                ('radiacion_solar', models.FloatField(blank=True, null=True)),
                ('sonda', models.ForeignKey(db_column='sonda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clima.sonda')),
            ],
        ),
    ]
