# Generated by Django 3.2.3 on 2021-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonda',
            name='inicio_actividad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
