# Generated by Django 3.2.3 on 2021-07-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_alter_sonda_inicio_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclimaticos',
            name='sonda',
            field=models.ForeignKey(db_column='sonda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_climaticos_set', to='clima.sonda'),
        ),
    ]
