# Generated by Django 3.2.3 on 2021-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0004_auto_20210715_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclimaticos',
            name='direccion_viento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
